--------------------------------------------------------------------
-- TABLA: parametros_sistema
--------------------------------------------------------------------
CREATE TABLE parametros_sistema (
   id_parametro         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   nombre_parametro     VARCHAR2(80) NOT NULL UNIQUE,
   valor_parametro      VARCHAR2(400),
   tipo_parametro       VARCHAR2(30),
   descripcion          VARCHAR2(300),
   usuario_modificacion VARCHAR2(120),
   fecha_modificacion   TIMESTAMP DEFAULT SYSTIMESTAMP,
   estado               CHAR(1) DEFAULT 'A'
      CHECK ( estado IN ('A','I') )
);
/
--------------------------------------------------------------------
-- TABLA: backup_logs
--------------------------------------------------------------------
CREATE TABLE backup_logs (
   id_backup       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   tipo_backup     VARCHAR2(30),
   fecha_backup    TIMESTAMP DEFAULT SYSTIMESTAMP,
   ruta_archivo    VARCHAR2(300),
   tamano_mb       NUMBER(12,2),
   usuario_ejecuta VARCHAR2(120),
   resultado       VARCHAR2(30),
   detalle_error   VARCHAR2(400),
   fecha_creacion  TIMESTAMP DEFAULT SYSTIMESTAMP
);
/
--------------------------------------------------------------------
-- TABLA: tipo_reporte
--------------------------------------------------------------------
CREATE TABLE tipo_reporte (
   id_tipo_reporte NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   nombre_reporte  VARCHAR2(120) NOT NULL,
   descripcion     VARCHAR2(300),
   sql_base        CLOB,
   categoria       VARCHAR2(60),
   estado          CHAR(1) DEFAULT 'A'
      CHECK ( estado IN ('A','I') ),
   fecha_creacion  TIMESTAMP DEFAULT SYSTIMESTAMP
);
/
--------------------------------------------------------------------
-- TABLA: reportes_generados
--------------------------------------------------------------------
CREATE TABLE reportes_generados (
   id_reporte_generado NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   id_tipo_reporte     NUMBER NOT NULL,
   id_usuario          NUMBER NOT NULL,
   parametros_json     CLOB,
   ruta_archivo        VARCHAR2(300),
   formato_salida      VARCHAR2(30),
   estado              VARCHAR2(30),
   fecha_creacion      TIMESTAMP DEFAULT SYSTIMESTAMP,
   CONSTRAINT fk_rg_tipo FOREIGN KEY (id_tipo_reporte)
      REFERENCES tipo_reporte (id_tipo_reporte),
   CONSTRAINT fk_rg_user FOREIGN KEY (id_usuario)
      REFERENCES usuarios (id_usuario)
);
/






CREATE OR REPLACE PROCEDURE generar_reporte (
    p_fecha_inicio IN DATE,
    p_fecha_fin IN DATE,
    p_id_usuario IN NUMBER,
    p_tipo_reporte IN VARCHAR2
) AS
BEGIN
    -- Insertar reporte generado en la tabla reportes_generados
    INSERT INTO reportes_generados (
        id_tipo_reporte,
        id_usuario,
        parametros_json,
        estado,
        fecha_creacion
    ) VALUES (
        p_tipo_reporte, 
        p_id_usuario, 
        '{"fecha_inicio": "' || TO_CHAR(p_fecha_inicio, 'YYYY-MM-DD') || '", "fecha_fin": "' || TO_CHAR(p_fecha_fin, 'YYYY-MM-DD') || '"}',
        'Enviado',  -- El reporte comienza con el estado 'Enviado'
        SYSDATE
    );

    COMMIT;
END generar_reporte;
/
CREATE OR REPLACE PROCEDURE consultar_reportes (
    p_id_usuario IN NUMBER
) AS
BEGIN
    -- Administradores pueden ver todos los reportes, vendedores solo los suyos
    FOR reporte IN (
        SELECT 
            rg.id_reporte_generado, 
            tr.nombre_reporte, 
            rg.fecha_creacion, 
            rg.estado, 
            rg.ruta_archivo,
            rg.formato_salida
        FROM reportes_generados rg
        JOIN tipo_reporte tr ON rg.id_tipo_reporte = tr.id_tipo_reporte
        WHERE rg.id_usuario = p_id_usuario
        OR EXISTS (
            SELECT 1 FROM usuarios u WHERE u.id_usuario = p_id_usuario AND u.rol = 'admin'
        )
        ORDER BY rg.fecha_creacion DESC
    ) LOOP
        -- Aquí se pueden hacer operaciones o imprimir resultados si se desea
        DBMS_OUTPUT.PUT_LINE('Reporte: ' || reporte.nombre_reporte || ' - Estado: ' || reporte.estado);
    END LOOP;
END consultar_reportes;
/

CREATE OR REPLACE TRIGGER trg_actualizar_estado_reporte
AFTER UPDATE OF estado ON reportes_generados
FOR EACH ROW
BEGIN
    -- Solo los administradores pueden actualizar el estado de los reportes
    IF :NEW.estado = 'Completado' AND :NEW.id_usuario IN (
        SELECT id_usuario FROM usuarios WHERE rol = 'admin' -- Verificamos si el usuario es admin
    ) THEN
        UPDATE reportes_generados
        SET estado = 'Completado', fecha_creacion = SYSTIMESTAMP
        WHERE id_reporte_generado = :NEW.id_reporte_generado;
    END IF;
END;
/

CREATE OR REPLACE VIEW vista_reportes_diarios AS
SELECT 
    rg.id_reporte_generado, 
    tr.nombre_reporte, 
    rg.fecha_creacion, 
    rg.estado, 
    rg.ruta_archivo, 
    rg.formato_salida
FROM reportes_generados rg
JOIN tipo_reporte tr ON rg.id_tipo_reporte = tr.id_tipo_reporte
WHERE TRUNC(rg.fecha_creacion) = TRUNC(SYSDATE);  -- Filtra por el día de hoy
/

CREATE OR REPLACE VIEW vista_reportes_mensuales AS
SELECT 
    rg.id_reporte_generado, 
    tr.nombre_reporte, 
    rg.fecha_creacion, 
    rg.estado, 
    rg.ruta_archivo, 
    rg.formato_salida
FROM reportes_generados rg
JOIN tipo_reporte tr ON rg.id_tipo_reporte = tr.id_tipo_reporte
WHERE EXTRACT(MONTH FROM rg.fecha_creacion) = EXTRACT(MONTH FROM SYSDATE)
AND EXTRACT(YEAR FROM rg.fecha_creacion) = EXTRACT(YEAR FROM SYSDATE);  -- Filtra por el mes actual
/

CREATE OR REPLACE VIEW vista_reportes_anuales AS
SELECT 
    rg.id_reporte_generado, 
    tr.nombre_reporte, 
    rg.fecha_creacion, 
    rg.estado, 
    rg.ruta_archivo, 
    rg.formato_salida
FROM reportes_generados rg
JOIN tipo_reporte tr ON rg.id_tipo_reporte = tr.id_tipo_reporte
WHERE EXTRACT(YEAR FROM rg.fecha_creacion) = EXTRACT(YEAR FROM SYSDATE);  -- Filtra por el año actual
/


CREATE OR REPLACE VIEW vista_reportes_inventario AS
SELECT 
    rg.id_reporte_generado, 
    tr.nombre_reporte, 
    rg.fecha_creacion, 
    rg.estado, 
    rg.ruta_archivo, 
    rg.formato_salida
FROM reportes_generados rg
JOIN tipo_reporte tr ON rg.id_tipo_reporte = tr.id_tipo_reporte
WHERE tr.categoria = 'Inventario';  -- Filtra por la categoría 'Inventario'
/

CREATE OR REPLACE VIEW vista_reportes_compras AS
SELECT 
    rg.id_reporte_generado, 
    tr.nombre_reporte, 
    rg.fecha_creacion, 
    rg.estado, 
    rg.ruta_archivo, 
    rg.formato_salida
FROM reportes_generados rg
JOIN tipo_reporte tr ON rg.id_tipo_reporte = tr.id_tipo_reporte
WHERE tr.categoria = 'Compra';  -- Filtra por la categoría 'Compra'
/