



CREATE TABLE usuarios (
    id_usuario            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                VARCHAR2(100),
    usuario               VARCHAR2(50) UNIQUE NOT NULL,
    email                 VARCHAR2(120) UNIQUE NOT NULL,
    contrasena_hash       VARCHAR2(255) NOT NULL,
    telefono              VARCHAR2(20),
    estado                NUMBER(1) DEFAULT 1,
    fecha_creacion        DATE DEFAULT SYSDATE,
    fecha_ultimo_acceso   DATE
);


CREATE TABLE roles (
    id_rol          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol      VARCHAR2(50) NOT NULL UNIQUE,
    descripcion     VARCHAR2(200),
    estado          NUMBER(1) DEFAULT 1,
    fecha_creacion  DATE DEFAULT SYSDATE
);


CREATE TABLE permisos (
    id_permiso      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_permiso  VARCHAR2(100) NOT NULL UNIQUE,
    categoria       VARCHAR2(50),
    estado          NUMBER(1) DEFAULT 1,
    fecha_creacion  DATE DEFAULT SYSDATE
);



CREATE TABLE roles_permisos (
    id_rol       NUMBER NOT NULL,
    id_permiso   NUMBER NOT NULL,

    CONSTRAINT pk_roles_permisos PRIMARY KEY (id_rol, id_permiso),
    CONSTRAINT fk_rp_rol        FOREIGN KEY (id_rol) REFERENCES roles(id_rol),
    CONSTRAINT fk_rp_permiso    FOREIGN KEY (id_permiso) REFERENCES permisos(id_permiso)
);

CREATE TABLE empresas (
    id_empresa        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            VARCHAR2(150) NOT NULL,
    cedula_juridica   VARCHAR2(20),
    direccion         VARCHAR2(250),
    telefono          VARCHAR2(20),
    email             VARCHAR2(120),
    logo              VARCHAR2(500),
    estado            NUMBER(1) DEFAULT 1,
    fecha_creacion    DATE DEFAULT SYSDATE
);



CREATE TABLE usuarios_empresas (
    id_usuario    NUMBER NOT NULL,
    id_empresa    NUMBER NOT NULL,
    id_rol        NUMBER NOT NULL, 
    fecha_asignacion DATE DEFAULT SYSDATE,

    CONSTRAINT pk_usuarios_empresas PRIMARY KEY (id_usuario, id_empresa),
    CONSTRAINT fk_ue_usuario  FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario),
    CONSTRAINT fk_ue_empresa  FOREIGN KEY (id_empresa) REFERENCES empresas(id_empresa),
    CONSTRAINT fk_ue_rol      FOREIGN KEY (id_rol) REFERENCES roles(id_rol)
);



CREATE TABLE log_sesiones (
    id_sesion      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario     NUMBER NOT NULL,
    ip_origen      VARCHAR2(60),
    dispositivo    VARCHAR2(150),
    descripcion    VARCHAR2(300),
    fecha_inicio   DATE DEFAULT SYSDATE,
    fecha_cierre   DATE,
    estado         NUMBER(1),

    CONSTRAINT fk_ls_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
);




CREATE TABLE log_actividades (
    id_log         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario     NUMBER NOT NULL,
    modulo         VARCHAR2(100),
    accion         VARCHAR2(100),
    objeto         VARCHAR2(150),
    descripcion    CLOB,
    ip_origen      VARCHAR2(60),
    fecha_accion   DATE DEFAULT SYSDATE,

    CONSTRAINT fk_la_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
);



CREATE TABLE secciones_usuario (
    id_seccion        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario        NUMBER NOT NULL,
    nombre_seccion    VARCHAR2(100),
    descripcion       VARCHAR2(300),
    fecha_asignacion  DATE DEFAULT SYSDATE,

    CONSTRAINT fk_su_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
);
