--Tables
CREATE TABLE usuarios (
    id_usuario            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                VARCHAR2(100),
    usuario               VARCHAR2(50) UNIQUE NOT NULL,
    email                 VARCHAR2(120) UNIQUE NOT NULL,
    contrasena_hash       VARCHAR2(255) NOT NULL,
    telefono              VARCHAR2(20),
    estado                NUMBER(1) DEFAULT 1,
    fecha_creacion        DATE DEFAULT SYSDATE,
    fecha_ultimo_acceso   DATE
);


CREATE TABLE roles (
    id_rol          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol      VARCHAR2(50) NOT NULL UNIQUE,
    descripcion     VARCHAR2(200),
    estado          NUMBER(1) DEFAULT 1,
    fecha_creacion  DATE DEFAULT SYSDATE
);


CREATE TABLE permisos (
    id_permiso      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_permiso  VARCHAR2(100) NOT NULL UNIQUE,
    categoria       VARCHAR2(50),
    estado          NUMBER(1) DEFAULT 1,
    fecha_creacion  DATE DEFAULT SYSDATE
);



CREATE TABLE roles_permisos (
    id_rol       NUMBER NOT NULL,
    id_permiso   NUMBER NOT NULL,
    CONSTRAINT pk_roles_permisos PRIMARY KEY (id_rol, id_permiso),
    CONSTRAINT fk_rp_rol     FOREIGN KEY (id_rol) REFERENCES roles(id_rol),
    CONSTRAINT fk_rp_permiso FOREIGN KEY (id_permiso) REFERENCES permisos(id_permiso)
);


CREATE TABLE empresas (
    id_empresa        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            VARCHAR2(150) NOT NULL,
    cedula_juridica   VARCHAR2(20),
    direccion         VARCHAR2(250),
    telefono          VARCHAR2(20),
    email             VARCHAR2(120),
    logo              VARCHAR2(500),
    estado            NUMBER(1) DEFAULT 1,
    fecha_creacion    DATE DEFAULT SYSDATE
);



CREATE TABLE usuarios_empresas (
    id_usuario    NUMBER NOT NULL,
    id_empresa    NUMBER NOT NULL,
    id_rol        NUMBER NOT NULL, 
    fecha_asignacion DATE DEFAULT SYSDATE,
    CONSTRAINT pk_usuarios_empresas PRIMARY KEY (id_usuario, id_empresa),
    CONSTRAINT fk_ue_usuario  FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario),
    CONSTRAINT fk_ue_empresa  FOREIGN KEY (id_empresa) REFERENCES empresas(id_empresa),
    CONSTRAINT fk_ue_rol      FOREIGN KEY (id_rol) REFERENCES roles(id_rol)
);



CREATE TABLE log_sesiones (
    id_sesion      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario     NUMBER NOT NULL,
    ip_origen      VARCHAR2(60),
    dispositivo    VARCHAR2(150),
    descripcion    VARCHAR2(300),
    fecha_inicio   DATE DEFAULT SYSDATE,
    fecha_cierre   DATE,
    estado         NUMBER(1),
    CONSTRAINT fk_ls_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
);




CREATE TABLE log_actividades (
    id_log         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario     NUMBER NOT NULL,
    modulo         VARCHAR2(100),
    accion         VARCHAR2(100),
    objeto         VARCHAR2(150),
    descripcion    CLOB,
    ip_origen      VARCHAR2(60),
    fecha_accion   DATE DEFAULT SYSDATE,
    CONSTRAINT fk_la_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
);



CREATE TABLE secciones_usuario (
    id_seccion        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario        NUMBER NOT NULL,
    nombre_seccion    VARCHAR2(100),
    descripcion       VARCHAR2(300),
    fecha_asignacion  DATE DEFAULT SYSDATE,
    CONSTRAINT fk_su_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
);










-- Insercion de Roles
INSERT INTO roles (nombre_rol, descripcion, estado, fecha_creacion)
VALUES ('admin', 'Rol con permisos de administrador', 1, SYSDATE);


INSERT INTO roles (nombre_rol, descripcion, estado, fecha_creacion)
VALUES ('vendedor', 'Rol para usuarios que realizan ventas', 1, SYSDATE);








CREATE OR REPLACE PROCEDURE sp_crear_empresa (
    p_nombre            IN empresas.nombre%TYPE,
    p_cedula_juridica   IN empresas.cedula_juridica%TYPE,
    p_direccion         IN empresas.direccion%TYPE,
    p_telefono          IN empresas.telefono%TYPE,
    p_email             IN empresas.email%TYPE,
    o_id_empresa        OUT NUMBER
)
AS
BEGIN
    INSERT INTO empresas (nombre, cedula_juridica, direccion, telefono, email)
    VALUES (p_nombre, p_cedula_juridica, p_direccion, p_telefono, p_email)
    RETURNING id_empresa INTO o_id_empresa;
END sp_crear_empresa;
/



CREATE OR REPLACE PROCEDURE sp_crear_usuario (
    p_nombre       IN usuarios.nombre%TYPE,
    p_usuario      IN usuarios.usuario%TYPE,
    p_email        IN usuarios.email%TYPE,
    p_telefono     IN usuarios.telefono%TYPE,
    p_hash         IN usuarios.contrasena_hash%TYPE,
    o_id_usuario   OUT NUMBER
)
AS
BEGIN
    INSERT INTO usuarios (nombre, usuario, email, telefono, contrasena_hash, estado)
    VALUES (p_nombre, p_usuario, p_email, p_telefono, p_hash, 1)
    RETURNING id_usuario INTO o_id_usuario;
END sp_crear_usuario;
/



CREATE OR REPLACE PROCEDURE sp_get_rol_admin (
    o_id_rol OUT NUMBER
)
AS
BEGIN
    SELECT id_rol INTO o_id_rol
    FROM roles
    WHERE nombre_rol = 'vendedor'
      AND estado = 1;
END sp_get_rol_admin;
/


CREATE OR REPLACE PROCEDURE sp_asignar_usuario_empresa (
    p_id_usuario    IN usuarios_empresas.id_usuario%TYPE,
    p_id_empresa    IN usuarios_empresas.id_empresa%TYPE,
    p_id_rol        IN usuarios_empresas.id_rol%TYPE
)
AS
BEGIN
    INSERT INTO usuarios_empresas (id_usuario, id_empresa, id_rol, fecha_asignacion)
    VALUES (p_id_usuario, p_id_empresa, p_id_rol, SYSDATE);
END sp_asignar_usuario_empresa;
/






CREATE OR REPLACE PROCEDURE sp_get_empresas_por_usuario(
    p_id_usuario IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_cursor FOR
        SELECT e.id_empresa,
               e.nombre,
               e.cedula_juridica,
               e.direccion,
               e.telefono,
               e.email,
               e.logo
        FROM empresas e
        JOIN usuarios_empresas ue ON e.id_empresa = ue.id_empresa
        WHERE ue.id_usuario = p_id_usuario;
END;
/



CREATE OR REPLACE PROCEDURE sp_get_usuarios_de_empresa(
    p_id_empresa IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_cursor FOR
        SELECT 
            u.id_usuario,
            u.nombre,
            u.usuario,
            u.email,
            r.nombre_rol
        FROM usuarios u
        JOIN usuarios_empresas ue ON u.id_usuario = ue.id_usuario
        JOIN roles r ON ue.id_rol = r.id_rol
        WHERE ue.id_empresa = p_id_empresa;
END;
/





CREATE OR REPLACE PROCEDURE SP_GET_USUARIO(
    p_usuario_o_email IN VARCHAR2,
    p_id_usuario OUT NUMBER,
    p_nombre OUT VARCHAR2,
    p_usuario OUT VARCHAR2,
    p_email OUT VARCHAR2,
    p_contrasena_hash OUT VARCHAR2,
    p_encontrado OUT NUMBER
) AS
BEGIN
    p_encontrado := 0;

    SELECT id_usuario, nombre, usuario, email, contrasena_hash
    INTO p_id_usuario, p_nombre, p_usuario, p_email, p_contrasena_hash
    FROM usuarios
    WHERE usuario = p_usuario_o_email OR email = p_usuario_o_email;

    p_encontrado := 1;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        p_encontrado := 0;
    WHEN TOO_MANY_ROWS THEN
        p_encontrado := -1;
END SP_GET_USUARIO;
/



CREATE OR REPLACE PROCEDURE SP_UPDATE_ACCESO(
    p_id_usuario IN NUMBER
) AS
BEGIN
    UPDATE usuarios
    SET fecha_ultimo_acceso = SYSDATE
    WHERE id_usuario = p_id_usuario;

    COMMIT;
END SP_UPDATE_ACCESO;
/






CREATE OR REPLACE PROCEDURE SP_CHECK_USUARIO(
    p_usuario IN VARCHAR2,
    p_email IN VARCHAR2,
    p_existe OUT NUMBER
) AS
BEGIN
    SELECT COUNT(*)
    INTO p_existe
    FROM usuarios
    WHERE usuario = p_usuario OR email = p_email;
END SP_CHECK_USUARIO;
/





CREATE OR REPLACE PROCEDURE SP_INSERT_USUARIO(
    p_nombre IN VARCHAR2,
    p_usuario IN VARCHAR2,
    p_email IN VARCHAR2,
    p_contrasena_hash IN VARCHAR2,
    p_telefono IN VARCHAR2,
    p_id_usuario OUT NUMBER
) AS
BEGIN
    INSERT INTO usuarios (nombre, usuario, email, contrasena_hash, telefono, estado)
    VALUES (p_nombre, p_usuario, p_email, p_contrasena_hash, p_telefono, 1)
    RETURNING id_usuario INTO p_id_usuario;
END SP_INSERT_USUARIO;
/



CREATE OR REPLACE PROCEDURE SP_GET_EMPRESA(
    p_nombre IN VARCHAR2,
    p_id_empresa OUT NUMBER,
    p_encontrada OUT NUMBER
) AS
BEGIN
    p_encontrada := 0;
    SELECT id_empresa
    INTO p_id_empresa
    FROM empresas
    WHERE LOWER(nombre) = LOWER(p_nombre) AND estado = 1;
    p_encontrada := 1;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        p_encontrada := 0;
END SP_GET_EMPRESA;
/





CREATE OR REPLACE PROCEDURE SP_GET_ROL(
    p_nombre_rol IN VARCHAR2,
    p_id_rol OUT NUMBER,
    p_encontrado OUT NUMBER
) AS
BEGIN
    p_encontrado := 0;
    SELECT id_rol
    INTO p_id_rol
    FROM roles
    WHERE LOWER(nombre_rol) = LOWER(p_nombre_rol) AND estado = 1;
    p_encontrado := 1;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        p_encontrado := 0;
END SP_GET_ROL;
/





CREATE OR REPLACE PROCEDURE SP_ASIGNAR_USUARIO_EMPRESA(
    p_id_usuario IN NUMBER,
    p_id_empresa IN NUMBER,
    p_id_rol IN NUMBER
) AS
BEGIN
    INSERT INTO usuarios_empresas (id_usuario, id_empresa, id_rol, fecha_asignacion)
    VALUES (p_id_usuario, p_id_empresa, p_id_rol, SYSDATE);
END SP_ASIGNAR_USUARIO_EMPRESA;
/

--------------------------------------------------------------------
-- Cambiar estado de un usuario (activo/inactivo) YML
--------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_CAMBIAR_ESTADO_USUARIO(
    p_id_usuario   IN usuarios.id_usuario%TYPE,
    p_nuevo_estado IN usuarios.estado%TYPE
) AS
BEGIN
    UPDATE usuarios
    SET    estado = p_nuevo_estado
    WHERE  id_usuario = p_id_usuario;
END SP_CAMBIAR_ESTADO_USUARIO;
/
--------------------------------------------------------------------
-- Cambiar estado de una empresa (activa/inactiva) YML
--------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_CAMBIAR_ESTADO_EMPRESA(
    p_id_empresa   IN empresas.id_empresa%TYPE,
    p_nuevo_estado IN empresas.estado%TYPE
) AS
BEGIN
    UPDATE empresas
    SET    estado = p_nuevo_estado
    WHERE  id_empresa = p_id_empresa;
END SP_CAMBIAR_ESTADO_EMPRESA;
/
--------------------------------------------------------------------
-- Actualizar datos básicos de usuario YML
--    Si algún parámetro viene NULL, se mantiene el valor actual.
--------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_DATOS_USUARIO(
    p_id_usuario IN usuarios.id_usuario%TYPE,
    p_nombre     IN usuarios.nombre%TYPE,
    p_email      IN usuarios.email%TYPE,
    p_telefono   IN usuarios.telefono%TYPE
) AS
BEGIN
    UPDATE usuarios
    SET    nombre   = NVL(p_nombre,   nombre),
           email    = NVL(p_email,    email),
           telefono = NVL(p_telefono, telefono)
    WHERE  id_usuario = p_id_usuario;
END SP_ACTUALIZAR_DATOS_USUARIO;
/
--------------------------------------------------------------------
-- Actualizar datos básicos de empresa YML
--    Si algún parámetro viene NULL, se mantiene el valor actual.
--------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_DATOS_EMPRESA(
    p_id_empresa      IN empresas.id_empresa%TYPE,
    p_nombre          IN empresas.nombre%TYPE,
    p_cedula_juridica IN empresas.cedula_juridica%TYPE,
    p_direccion       IN empresas.direccion%TYPE,
    p_telefono        IN empresas.telefono%TYPE,
    p_email           IN empresas.email%TYPE,
    p_logo            IN empresas.logo%TYPE
) AS
BEGIN
    UPDATE empresas
    SET    nombre          = NVL(p_nombre,          nombre),
           cedula_juridica = NVL(p_cedula_juridica, cedula_juridica),
           direccion       = NVL(p_direccion,       direccion),
           telefono        = NVL(p_telefono,        telefono),
           email           = NVL(p_email,           email),
           logo            = NVL(p_logo,            logo)
    WHERE  id_empresa = p_id_empresa;
END SP_ACTUALIZAR_DATOS_EMPRESA;
/
--------------------------------------------------------------------
-- Registrar inicio de sesión YML
--    Crea un registro en log_sesiones y devuelve el id_sesion.
--------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_REGISTRAR_SESION_INICIO(
    p_id_usuario  IN log_sesiones.id_usuario%TYPE,
    p_ip_origen   IN log_sesiones.ip_origen%TYPE,
    p_dispositivo IN log_sesiones.dispositivo%TYPE,
    p_descripcion IN log_sesiones.descripcion%TYPE,
    o_id_sesion   OUT log_sesiones.id_sesion%TYPE
) AS
BEGIN
    INSERT INTO log_sesiones(
        id_usuario,
        ip_origen,
        dispositivo,
        descripcion,
        fecha_inicio,
        estado
    )
    VALUES(
        p_id_usuario,
        p_ip_origen,
        p_dispositivo,
        p_descripcion,
        SYSDATE,
        1 -- 1 = sesión activa
    )
    RETURNING id_sesion INTO o_id_sesion;
END SP_REGISTRAR_SESION_INICIO;
/
--------------------------------------------------------------------
-- Registrar cierre de sesión YML
--    Marca fecha_cierre y actualiza estado (ej: 0 = cerrada).
--------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_REGISTRAR_SESION_CIERRE(
    p_id_sesion    IN log_sesiones.id_sesion%TYPE,
    p_descripcion  IN log_sesiones.descripcion%TYPE,
    p_nuevo_estado IN log_sesiones.estado%TYPE
) AS
BEGIN
    UPDATE log_sesiones
    SET    fecha_cierre = SYSDATE,
           descripcion  = NVL(p_descripcion, descripcion),
           estado       = p_nuevo_estado
    WHERE  id_sesion = p_id_sesion;
END SP_REGISTRAR_SESION_CIERRE;
/
--------------------------------------------------------------------
-- Registrar actividad del usuario en un módulo YML
--------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_REGISTRAR_ACTIVIDAD(
    p_id_usuario  IN log_actividades.id_usuario%TYPE,
    p_modulo      IN log_actividades.modulo%TYPE,
    p_accion      IN log_actividades.accion%TYPE,
    p_objeto      IN log_actividades.objeto%TYPE,
    p_descripcion IN log_actividades.descripcion%TYPE,
    p_ip_origen   IN log_actividades.ip_origen%TYPE
) AS
BEGIN
    INSERT INTO log_actividades(
        id_usuario,
        modulo,
        accion,
        objeto,
        descripcion,
        ip_origen,
        fecha_accion
    )
    VALUES(
        p_id_usuario,
        p_modulo,
        p_accion,
        p_objeto,
        p_descripcion,
        p_ip_origen,
        SYSDATE
    );
END SP_REGISTRAR_ACTIVIDAD;
/
--------------------------------------------------------------------
--  Asignar permiso a un rol YML
--    Si ya existe la relación, no genera error (maneja DUP_VAL_ON_INDEX).
--------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_ASIGNAR_PERMISO_ROL(
    p_id_rol     IN roles_permisos.id_rol%TYPE,
    p_id_permiso IN roles_permisos.id_permiso%TYPE
) AS
BEGIN
    INSERT INTO roles_permisos(id_rol, id_permiso)
    VALUES (p_id_rol, p_id_permiso);
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        NULL; -- Ya existe, no hacemos nada
END SP_ASIGNAR_PERMISO_ROL;
/
--------------------------------------------------------------------
-- Remover permiso de un rol YML
--------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_REMOVER_PERMISO_ROL(
    p_id_rol     IN roles_permisos.id_rol%TYPE,
    p_id_permiso IN roles_permisos.id_permiso%TYPE
) AS
BEGIN
    DELETE FROM roles_permisos
    WHERE  id_rol     = p_id_rol
    AND    id_permiso = p_id_permiso;
END SP_REMOVER_PERMISO_ROL;
/
--------------------------------------------------------------------
--  Obtener permisos de un usuario en una empresa YML
--     Usa el rol asignado en usuarios_empresas y devuelve un cursor con
--     los permisos activos de ese usuario en esa empresa.
--------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_GET_PERMISOS_POR_USUARIO(
    p_id_usuario IN usuarios.id_usuario%TYPE,
    p_id_empresa IN empresas.id_empresa%TYPE,
    p_cursor     OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT DISTINCT
               p.id_permiso,
               p.nombre_permiso,
               p.categoria
        FROM   usuarios_empresas   ue
        JOIN   roles               r  ON ue.id_rol      = r.id_rol
        JOIN   roles_permisos      rp ON r.id_rol       = rp.id_rol
        JOIN   permisos            p  ON rp.id_permiso  = p.id_permiso
        WHERE  ue.id_usuario = p_id_usuario
        AND    ue.id_empresa = p_id_empresa
        AND    r.estado      = 1
        AND    p.estado      = 1;
END SP_GET_PERMISOS_POR_USUARIO;
/
