--TABLAS--
CREATE TABLE categoria_producto (
    id_categoria     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_categoria VARCHAR2(100) NOT NULL UNIQUE,
    codigo_categoria VARCHAR2(6) NOT NULL UNIQUE,
    descripcion      VARCHAR2(200),
    estado           CHAR(1) DEFAULT 'A' CHECK (estado IN ('A', 'I')),
    fecha_creacion   TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE proveedores (
    id_proveedor     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_proveedor VARCHAR2(120) NOT NULL,
    contacto         VARCHAR2(120),
    telefono         VARCHAR2(25),
    email            VARCHAR2(120),
    direccion        VARCHAR2(200),
    cedula_juridica  VARCHAR2(40),
    estado           CHAR(1) DEFAULT 'A' CHECK (estado IN ('A', 'I')),
    fecha_registro   TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE almacenes (
    id_almacen     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_almacen VARCHAR2(100) NOT NULL UNIQUE,
    responsable    VARCHAR2(120),
    telefono       VARCHAR2(25),
    direccion      VARCHAR2(200),
    estado         CHAR(1) DEFAULT 'A' CHECK (estado IN ('A', 'I')),
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE clientes (
    id_cliente     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_cliente VARCHAR2(120) NOT NULL,
    cedula         VARCHAR2(40),
    telefono       VARCHAR2(25),
    email          VARCHAR2(120),
    direccion      VARCHAR2(200),
    fecha_registro TIMESTAMP DEFAULT SYSTIMESTAMP,
    estado         CHAR(1) DEFAULT 'A' CHECK (estado IN ('A', 'I'))
);

CREATE TABLE descuentos (
    id_descuento     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_descuento VARCHAR2(120) NOT NULL,
    tipo_descuento   VARCHAR2(20) NOT NULL,
    valor_descuento  NUMBER(12,2) NOT NULL CHECK (valor_descuento >= 0),
    fecha_inicio     DATE,
    fecha_fin        DATE,
    id_producto      NUMBER,
    estado           CHAR(1) DEFAULT 'A' CHECK (estado IN ('A', 'I')),
    fecha_creacion   TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE productos (
    id_producto         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_producto     VARCHAR2(24) UNIQUE,
    nombre_producto     VARCHAR2(150) NOT NULL,
    descripcion         VARCHAR2(400),
    precio_venta        NUMBER(12,2) DEFAULT 0 NOT NULL CHECK (precio_venta >= 0),
    precio_compra       NUMBER(12,2) DEFAULT 0 NOT NULL CHECK (precio_compra >= 0),
    stock               NUMBER(12,2) DEFAULT 0 NOT NULL CHECK (stock >= 0),
    unidad_medida       VARCHAR2(20),
    id_categoria        NUMBER NOT NULL,
    id_proveedor        NUMBER,
    id_almacen          NUMBER,
    estado              CHAR(1) DEFAULT 'A' CHECK (estado IN ('A', 'I')),
    fecha_creacion      TIMESTAMP DEFAULT SYSTIMESTAMP,
    fecha_actualizacion TIMESTAMP,
    CONSTRAINT fk_prod_cat FOREIGN KEY (id_categoria)
        REFERENCES categoria_producto (id_categoria),
    CONSTRAINT fk_prod_prov FOREIGN KEY (id_proveedor)
        REFERENCES proveedores (id_proveedor),
    CONSTRAINT fk_prod_alma FOREIGN KEY (id_almacen)
        REFERENCES almacenes (id_almacen)
);

CREATE TABLE movimientos_inventario (
    id_movimiento    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto      NUMBER NOT NULL,
    tipo_movimiento  CHAR(1) NOT NULL CHECK (tipo_movimiento IN ('E', 'S', 'A')),
    cantidad         NUMBER(12,2) NOT NULL CHECK (cantidad > 0),
    referencia       VARCHAR2(60),
    motivo           VARCHAR2(200),
    id_almacen       NUMBER,
    stock_anterior   NUMBER(12,2),
    stock_nuevo      NUMBER(12,2),
    fecha_movimiento TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_mov_prod FOREIGN KEY (id_producto)
        REFERENCES productos (id_producto),
    CONSTRAINT fk_mov_alma FOREIGN KEY (id_almacen)
        REFERENCES almacenes (id_almacen)
);

CREATE TABLE metodos_pago (
    id_metodo_pago NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_metodo  VARCHAR2(60) NOT NULL UNIQUE,
    descripcion    VARCHAR2(200),
    estado         CHAR(1) DEFAULT 'A' CHECK (estado IN ('A', 'I')),
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE ventas (
    id_venta        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_venta    VARCHAR2(20) UNIQUE,
    id_usuario      NUMBER NOT NULL,
    id_cliente      NUMBER,
    id_metodo_pago  NUMBER,
    fecha_venta     TIMESTAMP DEFAULT SYSTIMESTAMP,
    descuento_total NUMBER(12,2) DEFAULT 0 NOT NULL,
    impuesto        NUMBER(12,2) DEFAULT 0 NOT NULL,
    subtotal        NUMBER(12,2) DEFAULT 0 NOT NULL,
    total           NUMBER(12,2) DEFAULT 0 NOT NULL,
    observacion     VARCHAR2(300),
    estado          VARCHAR2(20) DEFAULT 'REGISTRADA',
    fecha_creacion  TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_venta_user FOREIGN KEY (id_usuario)
        REFERENCES usuarios (id_usuario),
    CONSTRAINT fk_venta_cli FOREIGN KEY (id_cliente)
        REFERENCES clientes (id_cliente),
    CONSTRAINT fk_venta_pago FOREIGN KEY (id_metodo_pago)
        REFERENCES metodos_pago (id_metodo_pago)
);

CREATE TABLE detalle_ventas (
    id_detalle_venta   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta           NUMBER NOT NULL,
    id_producto        NUMBER NOT NULL,
    cantidad           NUMBER(12,2) NOT NULL CHECK (cantidad > 0),
    precio_unitario    NUMBER(12,2) NOT NULL CHECK (precio_unitario >= 0),
    descuento_unitario NUMBER(12,2) DEFAULT 0 NOT NULL CHECK (descuento_unitario >= 0),
    subtotal           NUMBER(12,2),
    impuesto           NUMBER(12,2) DEFAULT 0 NOT NULL CHECK (impuesto >= 0),
    total_linea        NUMBER(12,2),
    fecha_registro     TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_dv_venta FOREIGN KEY (id_venta)
        REFERENCES ventas (id_venta),
    CONSTRAINT fk_dv_prod FOREIGN KEY (id_producto)
        REFERENCES productos (id_producto)
);
/

--CODIGO DEL PRODUCTO--
CREATE SEQUENCE cod_unico START WITH 1 INCREMENT BY 1 NOCACHE;
/

--CODIGO DE VENTA--
CREATE SEQUENCE seq_cod_venta START WITH 1 INCREMENT BY 1 NOCACHE;
/

--TRIGGERS--
--GENERAR CODIGO DE PRODUCTO--
CREATE OR REPLACE TRIGGER trg_prod_sku_bi
BEFORE INSERT ON productos
FOR EACH ROW
DECLARE
    v_cod VARCHAR2(6);
    v_num NUMBER;
BEGIN
    IF :new.codigo_producto IS NULL THEN
        SELECT codigo_categoria INTO v_cod
        FROM categoria_producto
        WHERE id_categoria = :new.id_categoria;
        
        v_num := cod_unico.nextval;
        :new.codigo_producto := 'ZHN-' || v_cod || '-' || LPAD(v_num, 5, '0');
    END IF;
END;

--GENERAR CODIGO VENTA--
CREATE OR REPLACE TRIGGER trg_venta_codigo_bi 
BEFORE INSERT ON ventas
FOR EACH ROW
BEGIN
    IF :new.codigo_venta IS NULL THEN
        :new.codigo_venta := 'V' || TO_CHAR(seq_cod_venta.nextval, 'FM000000');
    END IF;
END;

--ACTUALIZAR STOCK AL FINALIZAR UNA VENTA--
CREATE OR REPLACE TRIGGER trg_venta_actualizar_stock
AFTER UPDATE OF estado ON ventas
FOR EACH ROW
WHEN (NEW.estado = 'REGISTRADA' AND OLD.estado = 'EN_PROCESO')
DECLARE
    CURSOR cur_productos IS
        SELECT id_producto, cantidad
        FROM detalle_ventas
        WHERE id_venta = :NEW.id_venta;
BEGIN
    FOR prod IN cur_productos LOOP
        UPDATE productos
        SET stock = stock - prod.cantidad,
            fecha_actualizacion = SYSTIMESTAMP
        WHERE id_producto = prod.id_producto;
        
        -- Registrar movimiento de inventario
        INSERT INTO movimientos_inventario (
            id_producto,
            tipo_movimiento,
            cantidad,
            referencia,
            motivo,
            stock_anterior,
            stock_nuevo
        ) VALUES (
            prod.id_producto,
            'S',
            prod.cantidad,
            'VENTA-' || :NEW.codigo_venta,
            'Venta registrada',
            fn_get_stock_producto(prod.id_producto) + prod.cantidad,
            fn_get_stock_producto(prod.id_producto)
        );
    END LOOP;
END;

--VERIFICAR STOCK ANTES DE AGREGAR UN DETALLE--
CREATE OR REPLACE TRIGGER trg_validar_stock_detalle
BEFORE INSERT ON detalle_ventas
FOR EACH ROW
DECLARE
    v_stock NUMBER;
BEGIN
    v_stock := fn_get_stock_producto(:NEW.id_producto);
    
    IF v_stock < :NEW.cantidad THEN
        RAISE_APPLICATION_ERROR(-20101, 
            'Stock insuficiente. Disponible: ' || v_stock);
    END IF;
END;
/

--FOREIGN KEY PARA podructos Y descuentos--
ALTER TABLE descuentos
    ADD CONSTRAINT fk_desc_prod FOREIGN KEY (id_producto)
        REFERENCES productos (id_producto);
/
  
--FUNCIONES--
--OBTENER STOCK DISPONIBLE DE UN PRODUCTO--
CREATE OR REPLACE FUNCTION fn_get_stock_producto(
    p_id_producto IN NUMBER
) RETURN NUMBER IS
    v_stock NUMBER;
BEGIN
    SELECT stock INTO v_stock
    FROM productos
    WHERE id_producto = p_id_producto AND estado = 'A';
    
    RETURN v_stock;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;

--OBTENER EL PRECIO DE VENTA DE UN PRODUCTO--
CREATE OR REPLACE FUNCTION fn_get_precio_producto(
    p_id_producto IN NUMBER
) RETURN NUMBER IS
    v_precio NUMBER;
BEGIN
    SELECT precio_venta INTO v_precio
    FROM productos
    WHERE id_producto = p_id_producto AND estado = 'A';
    
    RETURN v_precio;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;

--CALCULAR DESCUENTO DE UN PRODUCTO--
CREATE OR REPLACE FUNCTION fn_calcular_descuento(
    p_id_producto IN NUMBER,
    p_cantidad IN NUMBER,
    p_precio_unitario IN NUMBER
) RETURN NUMBER IS
    v_descuento NUMBER := 0;
    v_tipo VARCHAR2(20);
    v_valor NUMBER;
BEGIN
    SELECT tipo_descuento, valor_descuento
    INTO v_tipo, v_valor
    FROM descuentos
    WHERE id_producto = p_id_producto
      AND estado = 'A'
      AND (fecha_inicio IS NULL OR fecha_inicio <= SYSDATE)
      AND (fecha_fin IS NULL OR fecha_fin >= SYSDATE)
      AND ROWNUM = 1;
    
    IF v_tipo = 'PORCENTAJE' THEN
        v_descuento := (p_cantidad * p_precio_unitario * v_valor) / 100;
    ELSIF v_tipo = 'FIJO' THEN
        v_descuento := v_valor * p_cantidad;
    END IF;
    
    RETURN v_descuento;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;

--VALIDAR SI UN PRODUCTO EXISTE Y ESTA ACTIVO--
CREATE OR REPLACE FUNCTION fn_validar_producto(
    p_id_producto IN NUMBER
) RETURN NUMBER IS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM productos
    WHERE id_producto = p_id_producto AND estado = 'A';
    
    RETURN v_count;
END;

--OBTENER NOMBRE DE UN PRODUCTO--
CREATE OR REPLACE FUNCTION fn_get_nombre_producto(
    p_id_producto IN NUMBER
) RETURN VARCHAR2 IS
    v_nombre VARCHAR2(150);
BEGIN
    SELECT nombre_producto INTO v_nombre
    FROM productos
    WHERE id_producto = p_id_producto;
    
    RETURN v_nombre;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Producto no encontrado';
END;
/

--PROCEDIMIENTOS--
--LISTAR PRODUCTOS DISPONIBLES--
CREATE OR REPLACE PROCEDURE sp_listar_productos_disponibles(
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT 
            p.id_producto,
            p.codigo_producto,
            p.nombre_producto,
            p.descripcion,
            p.precio_venta,
            p.stock,
            p.unidad_medida,
            c.nombre_categoria,
            prov.nombre_proveedor
        FROM productos p
        INNER JOIN categoria_producto c ON p.id_categoria = c.id_categoria
        LEFT JOIN proveedores prov ON p.id_proveedor = prov.id_proveedor
        WHERE p.estado = 'A' AND p.stock > 0
        ORDER BY p.nombre_producto;
END;

--BUSCAR PRODUCTOS POR NOMBRE--
CREATE OR REPLACE PROCEDURE sp_buscar_productos(
    p_nombre IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT 
            p.id_producto,
            p.codigo_producto,
            p.nombre_producto,
            p.descripcion,
            p.precio_venta,
            p.stock,
            p.unidad_medida
        FROM productos p
        WHERE p.estado = 'A' 
          AND UPPER(p.nombre_producto) LIKE '%' || UPPER(p_nombre) || '%'
        ORDER BY p.nombre_producto;
END;

--INICIAR UNA VENTA--
CREATE OR REPLACE PROCEDURE sp_iniciar_venta(
    p_id_usuario IN NUMBER,
    p_id_cliente IN NUMBER,
    p_id_metodo_pago IN NUMBER,
    p_id_venta OUT NUMBER
) AS
BEGIN
    INSERT INTO ventas (
        id_usuario,
        id_cliente,
        id_metodo_pago,
        fecha_venta,
        estado
    ) VALUES (
        p_id_usuario,
        p_id_cliente,
        p_id_metodo_pago,
        SYSTIMESTAMP,
        'EN_PROCESO'
    ) RETURNING id_venta INTO p_id_venta;
    
    COMMIT;
END;

--AGREGAR DETALLES A UNA VENTA--
CREATE OR REPLACE PROCEDURE sp_agregar_detalle_venta(
    p_id_venta IN NUMBER,
    p_id_producto IN NUMBER,
    p_cantidad IN NUMBER,
    p_id_detalle OUT NUMBER
) AS
    v_precio NUMBER;
    v_descuento NUMBER;
    v_stock NUMBER;
BEGIN
    -- Validar stock
    v_stock := fn_get_stock_producto(p_id_producto);
    IF v_stock < p_cantidad THEN
        RAISE_APPLICATION_ERROR(-20100, 'Stock insuficiente');
    END IF;
    
    -- Obtener precio
    v_precio := fn_get_precio_producto(p_id_producto);
    
    -- Calcular descuento
    v_descuento := fn_calcular_descuento(p_id_producto, p_cantidad, v_precio);
    
    -- Insertar detalle
    INSERT INTO detalle_ventas (
        id_venta,
        id_producto,
        cantidad,
        precio_unitario,
        descuento_unitario,
        impuesto
    ) VALUES (
        p_id_venta,
        p_id_producto,
        p_cantidad,
        v_precio,
        v_descuento / p_cantidad,
        (v_precio * p_cantidad - v_descuento) * 0.13  -- IVA 13%
    ) RETURNING id_detalle_venta INTO p_id_detalle;
    
    COMMIT;
END;

--FINALIZAR UNA VENTA--
CREATE OR REPLACE PROCEDURE sp_finalizar_venta(
    p_id_venta IN NUMBER,
    p_observacion IN VARCHAR2 DEFAULT NULL
) AS
    v_subtotal NUMBER := 0;
    v_descuento_total NUMBER := 0;
    v_impuesto_total NUMBER := 0;
    v_total NUMBER := 0;
    
    CURSOR cur_detalle IS
        SELECT cantidad, precio_unitario, descuento_unitario, impuesto
        FROM detalle_ventas
        WHERE id_venta = p_id_venta;
BEGIN
    -- Calcular totales usando cursor
    FOR det IN cur_detalle LOOP
        v_subtotal := v_subtotal + (det.cantidad * det.precio_unitario);
        v_descuento_total := v_descuento_total + det.descuento_unitario;
        v_impuesto_total := v_impuesto_total + det.impuesto;
    END LOOP;
    
    v_total := v_subtotal - v_descuento_total + v_impuesto_total;
    
    -- Actualizar venta
    UPDATE ventas
    SET subtotal = v_subtotal,
        descuento_total = v_descuento_total,
        impuesto = v_impuesto_total,
        total = v_total,
        estado = 'REGISTRADA',
        observacion = p_observacion
    WHERE id_venta = p_id_venta;
    
    COMMIT;
END;

--CANCELAR UNA VENTA--
CREATE OR REPLACE PROCEDURE sp_cancelar_venta(
    p_id_venta IN NUMBER,
    p_motivo IN VARCHAR2
) AS
BEGIN
    UPDATE ventas
    SET estado = 'CANCELADA',
        observacion = p_motivo
    WHERE id_venta = p_id_venta;
    
    -- Restaurar stock
    UPDATE productos p
    SET stock = stock + (
        SELECT SUM(dv.cantidad)
        FROM detalle_ventas dv
        WHERE dv.id_venta = p_id_venta
          AND dv.id_producto = p.id_producto
    )
    WHERE id_producto IN (
        SELECT id_producto 
        FROM detalle_ventas 
        WHERE id_venta = p_id_venta
    );
    
    COMMIT;
END;

--OBTENER HISTORIAL DE VENTAS--
CREATE OR REPLACE PROCEDURE sp_historial_ventas(
    p_fecha_inicio IN DATE DEFAULT NULL,
    p_fecha_fin IN DATE DEFAULT NULL,
    p_id_usuario IN NUMBER DEFAULT NULL,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT 
            v.id_venta,
            v.codigo_venta,
            v.fecha_venta,
            u.nombre AS nombre_usuario,
            c.nombre_cliente,
            mp.nombre_metodo AS metodo_pago,
            v.subtotal,
            v.descuento_total,
            v.impuesto,
            v.total,
            v.estado
        FROM ventas v
        INNER JOIN usuarios u ON v.id_usuario = u.id_usuario
        LEFT JOIN clientes c ON v.id_cliente = c.id_cliente
        LEFT JOIN metodos_pago mp ON v.id_metodo_pago = mp.id_metodo_pago
        WHERE (p_fecha_inicio IS NULL OR TRUNC(v.fecha_venta) >= p_fecha_inicio)
          AND (p_fecha_fin IS NULL OR TRUNC(v.fecha_venta) <= p_fecha_fin)
          AND (p_id_usuario IS NULL OR v.id_usuario = p_id_usuario)
        ORDER BY v.fecha_venta DESC;
END;

--OBTENER DETALLES DE UNA VENTA ESPECIFICA--
CREATE OR REPLACE PROCEDURE sp_detalle_venta(
    p_id_venta IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT 
            dv.id_detalle_venta,
            p.codigo_producto,
            p.nombre_producto,
            dv.cantidad,
            dv.precio_unitario,
            dv.descuento_unitario,
            dv.subtotal,
            dv.impuesto,
            dv.total_linea
        FROM detalle_ventas dv
        INNER JOIN productos p ON dv.id_producto = p.id_producto
        WHERE dv.id_venta = p_id_venta
        ORDER BY dv.id_detalle_venta;
END;

--LISTAR METODOS DE PAGO--
CREATE OR REPLACE PROCEDURE sp_listar_metodos_pago(
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT id_metodo_pago, nombre_metodo, descripcion
        FROM metodos_pago
        WHERE estado = 'A'
        ORDER BY nombre_metodo;
END;

--LISTAR CLIENTES ACTIVOS--
CREATE OR REPLACE PROCEDURE sp_listar_clientes(
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT 
            id_cliente,
            nombre_cliente,
            cedula,
            telefono,
            email
        FROM clientes
        WHERE estado = 'A'
        ORDER BY nombre_cliente;
END;

--CREAR UN CLIENTE RAPIDO--
CREATE OR REPLACE PROCEDURE sp_crear_cliente_rapido(
    p_nombre IN VARCHAR2,
    p_cedula IN VARCHAR2,
    p_telefono IN VARCHAR2,
    p_id_cliente OUT NUMBER
) AS
BEGIN
    INSERT INTO clientes (
        nombre_cliente,
        cedula,
        telefono,
        estado
    ) VALUES (
        p_nombre,
        p_cedula,
        p_telefono,
        'A'
    ) RETURNING id_cliente INTO p_id_cliente;
    
    COMMIT;
END;
/

--VISTAS--
--VENTAS DEL DIA--
CREATE OR REPLACE VIEW v_ventas_hoy AS
SELECT 
    v.id_venta,
    v.codigo_venta,
    v.fecha_venta,
    u.nombre AS vendedor,
    c.nombre_cliente,
    v.total,
    v.estado
FROM ventas v
INNER JOIN usuarios u ON v.id_usuario = u.id_usuario
LEFT JOIN clientes c ON v.id_cliente = c.id_cliente
WHERE TRUNC(v.fecha_venta) = TRUNC(SYSDATE);

--PRODUCTOS MAS VENDIDOS--
CREATE OR REPLACE VIEW v_productos_mas_vendidos AS
SELECT 
    p.id_producto,
    p.codigo_producto,
    p.nombre_producto,
    SUM(dv.cantidad) AS total_vendido,
    SUM(dv.total_linea) AS ingreso_total
FROM productos p
INNER JOIN detalle_ventas dv ON p.id_producto = dv.id_producto
INNER JOIN ventas v ON dv.id_venta = v.id_venta
WHERE v.estado = 'REGISTRADA'
GROUP BY p.id_producto, p.codigo_producto, p.nombre_producto
ORDER BY total_vendido DESC;

--RESUMEN DE VENTAS POR VENDEDOR--
CREATE OR REPLACE VIEW v_ventas_por_vendedor AS
SELECT 
    u.id_usuario,
    u.nombre AS vendedor,
    COUNT(v.id_venta) AS total_ventas,
    SUM(v.total) AS monto_total,
    AVG(v.total) AS promedio_venta
FROM usuarios u
INNER JOIN ventas v ON u.id_usuario = v.id_usuario
WHERE v.estado = 'REGISTRADA'
GROUP BY u.id_usuario, u.nombre;

--PRODUCTOS CON STOCK BAJO--
CREATE OR REPLACE VIEW v_stock_bajo AS
SELECT 
    p.id_producto,
    p.codigo_producto,
    p.nombre_producto,
    p.stock,
    c.nombre_categoria
FROM productos p
INNER JOIN categoria_producto c ON p.id_categoria = c.id_categoria
WHERE p.stock < 10 AND p.estado = 'A'
ORDER BY p.stock;

--METODOS DE PAGO--
CREATE OR REPLACE VIEW v_ventas_por_metodo_pago AS
SELECT 
    mp.nombre_metodo,
    COUNT(v.id_venta) AS cantidad_ventas,
    SUM(v.total) AS total_vendido
FROM metodos_pago mp
LEFT JOIN ventas v ON mp.id_metodo_pago = v.id_metodo_pago
WHERE v.estado = 'REGISTRADA'
GROUP BY mp.nombre_metodo;
/
